name: Fonctionnalité à ajouter
description: Fonctionnalité à développer pour le rendu du projet
labels: todo
body:
  - type: markdown
    attributes:
      value: |
        ## Fonctionnalité à ajouter
  - type: textarea
    validations:
      required: true
    attributes:
      label: Titre
      description: |
        Donnez un titre à la fonctionnalité demandée
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: |
        Que fera la fonctionnalité demandée ?
  - type: textarea
    validations:
      required: false
    attributes:
      label: Suggestion d'implémentation
      description: |
        Comment cette fonctionnalité pourrait être implémentée dans le code ?
